#-------------------------------------------------------------------------------
# Copyright 2019 Dominik Salvet
# SPDX-License-Identifier: MIT
# https://github.com/dominiksalvet/gim
#-------------------------------------------------------------------------------

os: linux
dist: xenial
language: shell

addons:
  apt:
    packages:
      - python3-pip

install:
  - pip3 install --user fsfe-reuse

before_script:
  - shellcheck --version
  - reuse --version

script:
  - shellcheck bash/* bin/* lib/gim/installers/* lib/gim/rc/* lib/gim/dbi lib/gim/path make/*
  - reuse lint

after_success:
  - make install
