#-------------------------------------------------------------------------------
# Copyright 2019 Dominik Salvet
# SPDX-License-Identifier: MIT
# https://github.com/dominiksalvet/gim
#-------------------------------------------------------------------------------

os: linux
dist: xenial
language: shell

jobs:
  include:
    - stage: checks
      name: Static analysis
      before_script: shellcheck --version
      script: shellcheck bash/* bin/* lib/gim/installers/* lib/gim/rc/* lib/gim/dbi lib/gim/path make/*

    - name: Licensing
      addons:
        apt:
          packages: python3-pip
      install: pip3 install --user fsfe-reuse
      before_script: reuse --version
      script: reuse lint

    - name: Global installation
      script:
        - sudo make install
        - gim_status="$(sudo gim status github.com/dominiksalvet/gim)"
        - echo "$gim_status" | grep -q -v 'nothing'

    - name: Local installation
      script:
        - make install
        - gim_status="$(gim status github.com/dominiksalvet/gim)"
        - echo "$gim_status" | grep -q -v 'nothing'
