#-------------------------------------------------------------------------------
# Copyright 2019 Dominik Salvet
# SPDX-License-Identifier: MIT
# https://github.com/dominiksalvet/gim
#-------------------------------------------------------------------------------

os: linux
dist: xenial
language: shell

jobs:
  include:
    - stage: checks
      name: Static analysis
      before_script: shellcheck --version
      script: shellcheck bash/* bin/* lib/gim/installers/* lib/gim/rc/* lib/gim/dbi lib/gim/path make/*

    - name: Licensing
      addons:
        apt:
          packages:
            - python3-pip
      before_script: reuse --version
      script: reuse lint

    - name: Installation
      script:
        - make install
        - gim status github.com/dominiksalvet/gim
