#-------------------------------------------------------------------------------
# Copyright 2019 Dominik Salvet
# SPDX-License-Identifier: MIT
# https://github.com/dominiksalvet/gim
#-------------------------------------------------------------------------------

os: linux
dist: xenial
language: shell

jobs:
  include:
    - stage: shellcheck
      before_script:
        - shellcheck --version
      script:
        - shellcheck bash/* bin/* lib/gim/installers/* lib/gim/rc/* lib/gim/dbi lib/gim/path make/*
    - stage: reuse
      addons:
        apt:
          packages:
            - python3-pip
      before_script:
        - reuse --version
      script:
        - reuse lint
