#-------------------------------------------------------------------------------
# Copyright 2019 Dominik Salvet
# SPDX-License-Identifier: MIT
# https://github.com/dominiksalvet/gim
#-------------------------------------------------------------------------------

os: linux
dist: xenial
language: shell

jobs:
  include:
    - stage: shellcheck
      before_script:
        - shellcheck --version
      script:
        - shellcheck bash/* bin/* lib/gim/installers/* lib/gim/rc/* lib/gim/dbi lib/gim/path make/*
    - stage: reuse
      lanuage: python
      python: 3.6
      addons:
        apt:
          packages:
            - python3-pip
      install:
        - pip3 install --user fsfe-reuse
      before_script:
        - python --version
        - python3 --version
        - reuse --version
      script:
        - reuse lint
