language: python
python: 3.6

addons:
  apt:
    packages:
      - python3-pip

install:
  - sudo pip3 install fsfe-reuse

before_script:
  - shellcheck --version
  - python3 --version
  - python --version
  - reuse --version

script:
  - shellcheck bash/* bin/* lib/gim/installers/* lib/gim/rc/* lib/gim/dbi lib/gim/path make/*
  - reuse lint

after_success:
  - make install
