language: shell
python: 3.5

addons:
  apt:
    packages:
      - python3
      - python3-pip

install:
  - pip3 install --user fsfe-reuse

before_script:
  - shellcheck --version
  - reuse --version

script:
  - shellcheck bash/* bin/* lib/gim/installers/* lib/gim/rc/* lib/gim/dbi lib/gim/path make/*
  - reuse lint
