#!/bin/sh

#-------------------------------------------------------------------------------
# Copyright 2018-2019 Dominik Salvet
# SPDX-License-Identifier: MIT
# https://gitlab.com/dominiksalvet/gim
#-------------------------------------------------------------------------------
# DESCRIPTION:
#   This file represents a gim installation script.
# PARAMETERS:
#   $1 - gim directory path
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# shellcheck disable=SC1090,SC2034
#-------------------------------------------------------------------------------


#-------------------------------------------------------------------------------
# INITIALIZATION
#-------------------------------------------------------------------------------

# gim library path is relative to the gim path and it must exist
GIM_LIB_DIR="$(cd -- "$1"/lib/gim/ && pwd)" &&

# load file path abstraction module
. "$GIM_LIB_DIR"/path &&

# check software dependencies
while read -r sw; do
    if ! command -v -- "$sw" > /dev/null; then
        echo "$0: missing $sw software" >&2
        return 1
    fi
done < "$(path_deps)" &&

# load the default RC file
. "$(path_default_rc)" &&

# overwrite default prefix if any delivered
GIM_PREFIX="${PREFIX:-"$GIM_PREFIX"}" &&

# load the configuration editor
. "$1"/make/ced &&

#-------------------------------------------------------------------------------
# INSTALLATION
#-------------------------------------------------------------------------------

# copy gim binary
mkdir -p "$GIM_PREFIX"/bin/ &&
cp "$1"/bin/gim "$GIM_PREFIX"/bin/ &&
# copy gim library
mkdir -p "$GIM_PREFIX"/lib/ &&
cp -R "$1"/lib/gim/ "$GIM_PREFIX"/lib/ &&

{ # add gim binary directory to PATH
ced_add_path_profile "$GIM_PREFIX"/bin gim-bin-path ||
echo "$0: can't add gim binary directory to PATH" >&2 # however, still continues
} &&
{ # install Bash tab completion
ced_add_bash_completion "$1"/bash/gim-prompt ||
echo "$0: can't set up Bash tab completion" >&2 # however, still continues
} &&

# if used installer is not gim, insert to gim database must be done here
if [ "$INSTALLER" != gim ]; then
    # get hash of the current git commit
    commit_hash="$(git rev-parse HEAD)" &&

    # overwrite default database directory path if any delivered
    GIM_DB_DIR="${DB_DIR:-"$GIM_DB_DIR"}" &&
    GIM_STATUS_PATH="$GIM_DB_DIR"/status && # derive gim status path

    # load gim database interface module
    . "$(path_dbi)" &&

    # insert gim to database
    dbi_init &&
    dbi_insert 'gitlab.com/dominiksalvet/gim' "$commit_hash" "$GIM_PREFIX"
fi
