#!/bin/sh

#-------------------------------------------------------------------------------
# Copyright 2018-2019 Dominik Salvet
# SPDX-License-Identifier: MIT
# https://github.com/dominiksalvet/gim
#-------------------------------------------------------------------------------
# DESCRIPTION:
#   This file represents a gim uninstallation script.
# PARAMETERS:
#   $1 - gim directory path
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# shellcheck disable=SC1090,SC1091,SC2034
#-------------------------------------------------------------------------------


#-------------------------------------------------------------------------------
# INITIALIZATION
#-------------------------------------------------------------------------------

# gim library path is relative to the gim directory path and it must exist
GIM_LIB_DIR="$(cd -- "$1"/lib/gim/ && pwd)" &&
# load file path abstraction module
. "$GIM_LIB_DIR"/path &&

# source required files
. "$(path_dbi)" && # gim database interface module
. "$1"/make/ced && # gim configuration editor module
. "$(path_default_rc)" && # gim default RC configuration

# either use a delivered value or use a default value from RC configuration
GIM_PREFIX="${PREFIX:-"$GIM_PREFIX"}" && # gim installation path prefix
GIM_DB_DIR="${DB_DIR:-"$GIM_DB_DIR"}" && # gim database directory path

# prepare the used variable values
GIM_STATUS_PATH="$GIM_DB_DIR"/status && # derive gim status path

#-------------------------------------------------------------------------------
# UNINSTALLATION
#-------------------------------------------------------------------------------

# remove gim binary
rm -f -- "${GIM_PREFIX:?}"/bin/gim &&
# remove gim library
rm -r -f -- "${GIM_PREFIX:?}"/lib/gim/ &&

# remove gim binary directory from PATH
ced_remove_profile gim-bin-path &&
# remove Bash tab completion
ced_remove_bash_completion gim-prompt &&

# if gim installer is not used, deletion from gim database must be done here
if [ "$INSTALLER" != gim ]; then
    dbi_init && # initialize gim database, then delete installation records
    dbi_delete 'github.com/dominiksalvet/gim'
fi
